---
### master headless service
### mysql-master-0.mysql-master-service.tomato.svc.cluster.local
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-service
  namespace: tomato
spec:
  selector:
    app: mysql-master
  clusterIP: None
  ports:
    - name: mysql-master-service-port
      protocol: TCP
      port: 3306
      targetPort: mysql
---
### MysqlMaster
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  namespace: tomato
spec:
  selector:
    matchLabels:
      app: mysql-master
  serviceName: mysql-master-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-master
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
        - name: init-conf
          image: mysql:8.4.7
          command:
            ["cp", "/mnt/configmap/master.cnf", "/etc/mysql/conf.d/my.cnf"]
          volumeMounts:
            ## mysql配置目录
            - name: conf
              mountPath: /etc/mysql/conf.d
            ## 绑定ConfigMap中的配置文件
            - name: mysql-master-config
              mountPath: /mnt/configmap
      containers:
        # mysql容器
        - name: mysql
          image: mysql:8.4.7
          ## 挂载root密码配置至环境变量
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - mysql -h 127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD -e "SELECT 1"
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            ## mysql配置目录
            - name: conf
              mountPath: /etc/mysql/conf.d
            ## 绑定ConfigMap中的配置文件
            - name: mysql-master-config
              mountPath: /mnt/configmap
            ## 数据文件绑定pvc
            - name: mysql-master-data
              mountPath: /var/lib/mysql
        - name: xtrabackup
          image: localhost/my-xtrabackup:8.4
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_MASTER_DUMP_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: MYSQL_MASTER_DUMP_USER
            - name: MYSQL_MASTER_DUMP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-master-secret
                  key: MYSQL_MASTER_DUMP_PASSWORD
          ports:
            - containerPort: 3307
              name: xtrabackup
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          command: ["bash", "/mnt/configmap/master_sidecar.sh"]
          volumeMounts:
            ## mysql配置目录
            - name: conf
              mountPath: /etc/mysql/conf.d
            ## 绑定ConfigMap中的配置文件
            - name: mysql-master-config
              mountPath: /mnt/configmap
            ## 数据文件绑定pvc
            - name: mysql-master-data
              mountPath: /var/lib/mysql
      volumes:
        # mysql配置目录
        - name: conf
          emptyDir: {}
        # ConfigMap配置作为配置文件
        - name: mysql-master-config
          configMap:
            name: mysql-master-cnf
            items:
              - key: master.cnf
                path: master.cnf
              - key: create_replication_account_procedure.sql
                path: create_replication_account_procedure.sql
              - key: master_sidecar.sh
                path: master_sidecar.sh
  volumeClaimTemplates:
    - metadata:
        name: mysql-master-data
      spec:
        storageClassName: standard # 使用local-path-provisioner
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
